// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feynkkjysiwfsumybvti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZleW5ra2p5c2l3ZnN1bXlidnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjM0NjUsImV4cCI6MjA3MzUzOTQ2NX0.pUNoGsGa_YWnRQP48c7Xly1GcKEcSsE1dMvFSJGOqoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});